/**
 * The global constants
 */
const MEGABYTE = 1024 * 1024;
export const CODE_ERROR = {
  /**
   * User Error
   * */
  EMAIL_EXISTS: "EMAIL_EXISTS",
  EMAIL_CONFIRMED: "EMAIL_HAS_BEEN_CONFIRMED",
  USER_EXISTS: 'USER_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_CANT_UPDATE_AVATAR: "USER_CANT_UPDATE_AVATAR:",
  PASSWORD_NOT_MATCH: 'PASSWORD_NOT_MATCH',
  CURRENT_PASSWORD_IS_INCORRECT: "CURRENT_PASSWORD_IS_INCORRECT",
  // The new password does not match the old password
  CHECK_OLD_AND_NEW_PASSWORD: "THE_NEW_PASSWORD_DOES_NOT_MATCH_THE_OLD_PASSWORD",
  // Error ID USER - TOKEN ID AND PRAMAS ID IS NOT DIFFERENT
  USER_ID_FAIL: "TOKEN_ID_AND_PRAMAS_ID_IS_NOT_DIFFERENT",
  // Logging out failed.
  USER_CANT_SIGNOUT: "LOGGING_OUT_FAILED",
  // Authentication code has expired.
  AUTHENTICATION_CODE_REGISTER_HAS_EXPIRED: "CODE_HAS_EXPIRED"
};

export const ADMIN_ROLE = {
  ROOT: 'root',
  ADMIN: 'admin'
};
