export namespace CONSTANT_API {
  export const API_ENDPOINTS = {
    GENRE: 'https://api.mangatea.live/v1/genre',
    LOGIN: 'https://api.mangatea.live/v1/user/login',
    SIGN_UP: 'https://api.mangatea.live/v1/user/register',
    PROFILE: 'https://api.mangatea.live/v1/user/me',
    MANGA: 'https://api.mangatea.live/v1/manga',
    UPLOAD_PROFILE_IMG: 'https://api.mangatea.live/v1/user/upload-avatar',
    COMMENT: 'https://api.mangatea.live/v1/comment',
    CHAPTER: 'https://api.mangatea.live/v1/chapter',
    MANGA_HOME: 'https://api.mangatea.live/v1/manga/home',
    GROUP_TRANSLATE: 'https://api.mangatea.live/v1/group',
    COUNTRY: 'https://api.mangatea.live/v1/country',
    MANGA_DISCUSSION: 'https://api.mangatea.live/v1/manga/suggestion',
    MEMBER: 'https://api.mangatea.live/v1/member/user',
    ADD_FAVORITE: 'https://api.mangatea.live/v1/member/add-to-favorite',
    REMOVE_FAVORITE: 'https://api.mangatea.live/v1/member/remove-from-favorite',
    SAVE_MANGA: 'https://api.mangatea.live/v1/member/save-manga',
    UNSAVED_MANGA:'https://api.mangatea.live/v1/member/unsaved-manga',
    RATING: 'https://api.mangatea.live/v1/rating',
    DASHBOARD: 'https://api.mangatea.live/v1/admin/dashboard',
    ADMIN_USER: 'https://api.mangatea.live/v1/user/find',
    ADMIN_BLOCK_USER: 'https://api.mangatea.live/v1/user/update-profile-admin',
    GROUP_TRANSLATE_UPLOAD_AVATAR: 'https://api.mangatea.live/v1/group/upload/',
    FORGOT_PASSWORD: 'http://localhost:2111/v1/user/forgot-password',
    RESET_PASSWORD: 'http://localhost:2111/v1/user/reset-password',
    MANGA_UPLOAD: 'http://localhost:2111/v1/user/manga-upload',
  }
}